---
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'debian/**'
      - 'doc/**'
    branches:
      - master
  pull_request:
    paths-ignore:
      - 'debian/**'
      - 'doc/**'
    branches:
      - master

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - id: cache-ccache
        uses: hendrikmuhs/ccache-action@v1

      - name: Install dependencies
        run: |
          sudo apt install -y --no-install-recommends \
            meson \
            libsystemd-dev \
            libpq-dev \
            libluajit-5.1-dev

      - name: Configure
        run: |
          meson setup \
            -Ddocumentation=disabled \
             --force-fallback-for=fmt \
            -Dwrap_mode=nofallback \
            output

      - name: Build
        run: ninja -C output -v
